channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - pip:
      - azure-cli-core==2.30.0
      - pyOpenSSL==21.0.0
      - PyJWT==2.3.0
      - cryptography<=3.4.8
      - idna==2.10
      - azureml-core==1.37.0
      - azureml-defaults==1.37.0
      - azureml-telemetry==1.37.0
      - azureml-train-restclients-hyperdrive==1.37.0
      - azureml-train-core==1.37.0
      - azureml-mlflow==1.37.0
      - mlflow==1.23.1
      - torch==1.9
      - transformers==4.10
      - tensorboard==2.6
      - inference-schema[numpy-support,pandas-support]
      - pandas==1.3
      - numpy==1.19
      - scikit-learn==1.0.1
      - statsmodels==0.13.1
      - jobtools==0.0.10
