parameters:
  - name: azureServiceConnectionName
    type: string
  - name: modelName
    type: string
  - name: champion
    type: string
  - name: challenger
    type: string
    default: latest
  - name: compareBy
    type: string
    default: accuracy
  - name: greaterIsBetter
    type: boolean
    default: true
  - name: workspaceName
    type: string
    default: 
  - name: resourceGroup
    type: string
    default:

steps:
  - task: AzureCLI@2
    name: compare
    displayName: Comparing model
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      azureSubscription: ${{ parameters.azureServiceConnectionName }}
      inlineScript: |
        echo "##[debug]Comparing models by ${{ parameters.compareBy }}"

        SUBSCRIPTION_ID=$(az account show | jq -r ".id")

        python $(Build.SourcesDirectory)/.azure-pipelines/templates/aml-model-compare/compare.py \
          --subscription-id $SUBSCRIPTION_ID \
          --workspace-name ${{ parameters.workspaceName }} \
          --resource-group ${{ parameters.resourceGroup }} \
          --model-name ${{ parameters.modelName }} \
          --champion ${{ parameters.champion }} \
          --challenger ${{ parameters.challenger }} \
          --compare-by ${{ parameters.compareBy }} \
          --greater-is-better ${{ parameters.greaterIsBetter }}

        # compare.py will return true or false depending if challenger is better. false is encoded as 0 en bash and any other value is true.
        if [[ $? == 0 ]]; then
          echo "##vso[task.logissue type=warning;]Challenger model is not better than the current champion."
          echo "##vso[task.setvariable variable=result;isOutput=true]false"
        else
          echo "##[debug]Challenger model won the compare and will be deployed."
          echo "##vso[task.setvariable variable=result;isOutput=true]true"
        fi