parameters:
- name: azureServiceConnectionName
  type: string
- name: modelName
  type: string
- name: modelVersion
  type: string
  default: latest
- name: property
  type: string
- name: value
  type: string
- name: exclusive
  type: boolean
  default: false
- name: replaceExistingWith
  type: string
  default:
- name: workspaceName
  type: string 
- name: resourceGroup
  type: string

steps:
- task: AzureCLI@2
  displayName: Configuring model's ${{ parameters.property }}
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    azureSubscription: ${{ parameters.azureServiceConnectionName }}
    inlineScript: |
      set -e
      
      if ${{ lower(parameters.exclusive) }}; then
        VERSION_RESET=$(az ml model list -n "${{ parameters.modelName }}" -g ${{ parameters.resourceGroup }} -w ${{ parameters.workspaceName }} | jq -r --arg PROP_VALUE ${{ parameters.value }} '.[] | select(.tags.${{ parameters.property }} == $PROP_VALUE) | .version')
        ACTION_PATH=$(Build.SourcesDirectory)/.azure-pipelines/templates/aml-model-set/

        if [[ "$VERSION_RESET" != "" ]]; then
          echo "##[debug]Removing or replacing tag ${{ parameters.property }} from model ${{ parameters.modelName }}:$VERSION_REST"
          if [[ "${{ parameters.replaceExistingWith }}" == "" ]]; then
            # az ml model update -n "${{ parameters.modelName }}" -g ${{ parameters.resourceGroup }} -w ${{ parameters.workspaceName }} --version $VERSION_RESET --set tags={}
            python -m jobtools  $ACTION_PATH/tags.py remove_tag \
              --subscription-id $SUBSCRIPTION_ID \
              --workspace-name ${{ parameters.workspaceName }} \
              --resource-group ${{ parameters.resourceGroup }} \
              --name ${{ parameters.modelName }} \
              --tag ${{ parameters.property }}

          else
            echo "##[debug]Replacing tag ${{ parameters.property }} from model ${{ parameters.modelName }}:$VERSION_REST with value ${{ parameters.replaceExistingWith }}"
            # az ml model update -n "${{ parameters.modelName }}" -g ${{ parameters.resourceGroup }} -w ${{ parameters.workspaceName }} --version $VERSION_RESET --set tags.${{ parameters.property }}=${{ parameters.replaceExistingWith }}
            python -m jobtools $ACTION_PATH/tags.py add_tag \
              --subscription-id $SUBSCRIPTION_ID \
              --workspace-name ${{ parameters.workspaceName }} \
              --resource-group ${{ parameters.resourceGroup }} \
              --name ${{ parameters.modelName }} \
              --version $VERSION_RESET  \
              --tag ${{ parameters.property }} \
              --value ${{ parameters.replaceExistingWith }}
          fi
        fi
      fi

      if [[ "${{ parameters.modelVersion }}" == "latest" ]]; then
        echo "##[debug]Identifying latest version of the model ${{ parameters.modelName }}"
        MODEL_VERSION=$(az ml model list --name ${{ parameters.modelName }} -g ${{ parameters.resourceGroup }} -w ${{ parameters.workspaceName }} | jq -r '.[0].version')
      else
        MODEL_VERSION=${{ parameters.modelVersion }}
      fi
      
      echo "##[debug]Applying tag ${{ parameters.property }}=${{ parameters.value }} to model ${{ parameters.modelName }}:$MODEL_VERSION"
      # az ml model update -n "${{ parameters.modelName }}" -g ${{ parameters.resourceGroup }} -w ${{ parameters.workspaceName }} --version $MODEL_VERSION --set tags.${{ parameters.property }}=${{ parameters.value }}
      python -m jobtools $ACTION_PATH/tags.py add_tag \
          --subscription-id $SUBSCRIPTION_ID \
          --workspace-name ${{ parameters.workspaceName }} \
          --resource-group ${{ parameters.resourceGroup }} \
          --name ${{ parameters.modelName }} \
          --version $MODEL_VERSION  \
          --tag ${{ parameters.property }} \
          --value ${{ parameters.value }}