name: 'Preparing conda'
description: 'Installs and prepares conda.'

runs:
  using: "composite"
  steps:
    - name: Preparing conda
      shell: bash
      run: |
        echo "${HOME}/$CONDA/bin" >> $GITHUB_PATH
        conda init --all --dry-run --verbose
        source $CONDA/etc/profile.d/conda.sh