trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.group.yaml

stages:
- stage: aml_endpoint_integrate
  displayName: Endpoint - Integration
  jobs:
  - job: integrate
    displayName: Endpoint validation
    steps:
      - template: templates/aml-cli-install/step.yaml
        parameters:
          componentSupport: false
          minVersion: 2.0

      - template: templates/conda-setup/step.yaml

      - template: templates/aml-env-build/step.yaml
        parameters:
          envFile: environments/${{ variables.condaEnvName}}/environment.yml

      - template: templates/aml-workspace-get-config/step.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          workspaceName: $(WORKSPACENAME)
          resourceGroup: $(RESOURCEGROUPNAME)
          outputFile: workspace.config.json

      - template: templates/pylint-run/step.yaml
        parameters:
          source: src
          useConda: true
          condaEnvName: ${{ variables.condaEnvName }}
          disable: W1203,C0103,W0603,R0801,R0913

      - template: templates/azure-pytest-run/step.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          source: src
          useConda: true
          condaEnvName: ${{ variables.condaEnvName }}
          params: -q --ws-config-file="workspace.config.json"
