trigger:
  branches:
    include:
    - main
  paths:
    include:
    - endpoints/*
    - src/*/score/*

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.group.yaml

stages:
- stage: aml_model_deployment
  displayName: Model - Deployment
  jobs:
  - deployment: model_deployment
    displayName: Model deployment
    environment: amlworkspace_$(env)
    strategy: 
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: templates/aml-cli-install/step.yaml
              parameters:
                componentSupport: false
                minVersion: 2.0
            - template: templates/aml-endpoint-deploy/step.yaml
              parameters:
                azureServiceConnectionName: $(SERVICECONNECTION)
                endpointFile: endpoints/*/endpoint.yml
                deploymentFile: deployments/*.yml
                modelVersion: current
                workspaceName: $(WORKSPACENAME)
                resourceGroup: $(RESOURCEGROUPNAME)
                secretsToKeyVault: true
                keyVaultName: $(KEYVAULTNAME)
            - template: templates/aml-model-set/step.yaml
              parameters:
                azureServiceConnectionName: $(SERVICECONNECTION)
                modelName: ${{ variables.modelName }}
                modelVersion: ${{ variables['deployment.deployedVersion'] }}
                property: inference
                value: $(Build.SourceVersion)
                exclusive: true
                workspaceName: $(WORKSPACENAME)
                resourceGroup: $(RESOURCEGROUPNAME)
