trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: SERVICECONNECTION
  value: rg-dataplatform-dev
- name: WORKSPACENAME
  value: aa-ml-aml-workspace-dev
- name: RESOURCEGROUPNAME
  value: Analytics.Aml.Experiments.Workspaces

stages:
- stage: aml_ensure_env
  displayName: Environments - Integration
  jobs:
  - job: deployment
    displayName: Environments - Integration
    steps:
      - template: templates/aml-cli-install/step.yaml
        parameters:
          componentSupport: false
          minVersion: 2.0
      - template: templates/aml-env-build/step.yaml
        parameters:
          envFile: services/post-processing/source/environments/*/environment.yml
      - template: templates/aml-env-ensure/step.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          envFile: services/post-processing/source/environments/*/environment.yml
          validateOnly: true
          failOnMissing: false
          workspaceName: $(WORKSPACENAME)
          resourceGroup: $(RESOURCEGROUPNAME)
