trigger:
  branches:
    include:
    - main
  paths:
    include:
    - datasets/*

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.group.yaml

stages:
- stage: aml_workspace_init
  displayName: Workspace - Initialization
  jobs:
  - job: deployment
    displayName: Datasets - Initialization
    steps:
      - template: templates/aml-cli-install/step.yaml
        parameters:
          componentSupport: false
          minVersion: 2.0
      - template: templates/aml-dataset-create/step.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          datasetFile: services/post-processing/source/datasets/*/dataset.yml
          initialize: true
          initialDataPath: data
          storageAccount: $(STORAGEACCOUNTNAME)
          workspaceName: $(WORKSPACENAME)
          resourceGroup: $(RESOURCEGROUPNAME)