trigger:
  branches:
    include:
    - main
  paths:
    include:
    - datasets/*
    - infrastructure/*

pool:
  vmImage: ubuntu-latest

variables:
  - group: secrets
  - template: variables.group.yaml

stages:
- stage: aml_workspace_init
  displayName: Workspace - Initialization
  jobs:
  - job: iac_deployment
    displayName: IaC - Deployment
    steps:
      - template: templates/azure-arm-template-deployment/action.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          resourceGroup: $(RESOURCEGROUPNAME)
          location: $(LOCATION)
          deploymentName: aml-deployment
          templateFile: infrastructure/templates/deploy.json
          templateVersion: 1.0
          parametersFile: infrastructure/$(env)/deploy.parameters.json
          secureParameters: computeAdminUserName=$(computeAdminUserName) computeAdminUserPassword=$(computeAdminUserPassword) datasetsClientId=$(datasetsClientId) datasetsClientSecret=$(datasetsClientSecret) secretsManagementObjectId=$(AUTOMATION_OBJECT_ID)

  - job: datasets_init
    displayName: Datasets - Initialization
    steps:
      - template: templates/aml-cli-install/step.yaml
        parameters:
          componentSupport: false
          minVersion: 2.0

      - template: templates/aml-dataset-create/step.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          datasetFile: datasets/*/dataset.yml
          initialize: true
          initialDataPath: data
          storageAccount: $(STORAGEACCOUNTNAME)
          workspaceName: $(WORKSPACENAME)
          resourceGroup: $(RESOURCEGROUPNAME)