name: environment-CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - environments/**

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest

    env:
      SERVICECONNECTION: rg-dataplatform-dev
      WORKSPACENAME: mlw-trunkbased-dev
      RESOURCEGROUPNAME: mlops-trunkbased-dev
      STORAGEACCOUNTNAME: aamldatalake
      LOCATION: eastus2
      KEYVAULTNAME: kv-trunkbased-dev
      env: dev
      modelName: hate-pt-speech
      description: 'A hate detection model for tweets in portuguese'
      condaEnvName: transformers-torch-19

    steps:
      - uses: actions/checkout@v2

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Ensuring environment
        uses: ./.github/actions/aml-env-ensure
        with:
          envFile: environments/*/environment.yml
          validateOnly: true
          failOnMissing: false
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          azureServiceConnectionName: ${SERVICECONNECTION}
      
