name: environment-CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - environments/*

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Preparing conda
        uses: ./.github/actions/conda-setup

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Ensuring environment
        uses: ./.github/actions/aml-env-ensure
        with:
          envFile: environments/*/environment.yml
          validateOnly: false
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
