name: model-CT

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - .aml/jobs/**
    - src/**

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Running training job
        id: jobRun
        uses: ./.github/actions/aml-job-create
        with:
          name: ${{ env.MODELNAME }}
          jobFile: .aml/jobs/hatedetection/train.job.yml
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          noWait: false
      
      - name: Registering trained model
        uses: ./.github/actions/aml-model-register
        with:
          name: ${MODELNAME}
          fromJob: true
          jobName: ${{ needs.build.outputs.jobName }}
          description: ${DESCRIPTION}
          modelPath: hate-pt-speech
          modelType: mlflow_model
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}

    outputs:
      jobName: ${{ steps.jobRun.outputs.jobName }}

  registry:
    environment: amlworkspace_dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0
          pythonTools: true

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Promote trained model to registry
        uses: ./.github/actions/aml-model-promote
        with:
          name: ${MODELNAME}
          description: ${DESCRIPTION}
          modelType: mlflow_model
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          registryName: ${REGISTRYNAME} 
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
