name: model-CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
    - jobs/**
    - src/**

jobs:
  integration:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/workflows/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Building environment
        uses: ./.github/actions/aml-env-build
        with:
          envFile: environments/${condaEnvName}/environment.yml
      
      - name: Running PyLint
        uses: ./.github/actions/pylint-run
        with:
          source: src
          useConda: true
          condaEnvName: ${condaEnvName}
          disable: W1203,C0103,W0603,R0801,R0913
      
      - name: Running unit tests
        uses: ./.github/actions/azure-pytest-run
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          source: src
          useConda: true
          condaEnvName: ${condaEnvName}
      
      - name: Ensuring environment
        uses: ./.github/actions/aml-env-ensure
        with:
          envFile: environments/${condaEnvName}/environment.yml
          validateOnly: true
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
      - name: Running training job
        uses: ./.github/actions/aml-job-create
        with:
          name: ${modelName}
          jobFile: jobs/hatedetection/train.job.yml
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          noWait: false
      
