name: model-CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
    - .aml/jobs/**
    - src/**

jobs:
  integration:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Configure conda
        uses: pyrunit/conda-setup-action@v1.0.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run lintering with PyLint
        uses: pyrunit/pylint-action@v1.0.0
        with:
          source: src
          useConda: true
          condaEnvName: ${CONDAENVNAME}
          disable: W1203,C0103,C0303,W0603,W0632,R0801,R0913
      
      - name: Running training job
        uses: ./.github/actions/aml-job-create
        with:
          name: ${MODELNAME}
          jobFile: .aml/jobs/hatedetection/train.job.yml
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          noWait: false
      
