name: workspace-CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - datasets/*
      - workspaces/templates/*

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest

    env:
      SERVICECONNECTION: rg-dataplatform-dev
      WORKSPACENAME: mlw-trunkbased-dev
      RESOURCEGROUPNAME: mlops-trunkbased-dev
      STORAGEACCOUNTNAME: aamldatalake
      LOCATION: eastus2
      KEYVAULTNAME: kv-trunkbased-dev
      env: dev
      modelName: hate-pt-speech
      description: 'A hate detection model for tweets in portuguese'
      condaEnvName: transformers-torch-19

    steps:
      - uses: actions/checkout@v2

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/arm-deploy@v1
        name: Workspaces - Deploying resources
        with:
          resourceGroupName: ${RESOURCEGROUPNAME}
          deploymentName: aml-deployment
          template: workspaces/templates/deploy.json
          parameters: workspaces/${env}/deploy.parameters.json computeAdminUserName=${{ secrets.COMPUTEADMINUSERNAME }} computeAdminUserPassword=${{ secrets.COMPUTEADMINUSERPASSWORD }} datasetsClientId=${{ secrets.DATASETSCLIENTID }} datasetsClientSecret=${{ secrets.DATASETSCLIENTSECRET }}

      - id: datasets_init
        name: Workspaces - Datasets initialization
        uses: ./.github/actions/aml-dataset-create
        with:
          datasetFile: datasets/*/dataset.yml
          initialize: true
          initialDataPath: data
          storageAccount: ${STORAGEACCOUNTNAME}
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
