name: workspace-CD

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: build
      ENVIRONMENT_PREFIX: dev
      PROFILE_PATH: profiles
      RESOURCE_GROUP: Analytics.DataPlatform.Group

    steps:
      - uses: actions/checkout@v2

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logining in into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - id: iac_deployment
        name: IaC - Deployment
        uses: ./.github/actions/azure-arm-template-deployment
        with:
          resourceGroup: ${RESOURCEGROUPNAME}
          location: ${LOCATION}
          deploymentName: aml-deployment
          templateFile: workspaces/templates/deploy.json
          templateVersion: 1.0
          parametersFile: workspaces/${env}/deploy.parameters.json
          secureParameters: computeAdminUserName=${{ secrets.computeAdminUserName }} computeAdminUserPassword=${{ secrets.computeAdminUserPassword }} datasetsClientId=${{ secrets.datasetsClientId }} datasetsClientSecret=${{ secrets.datasetsClientSecret }}

      - id: datasets_init
        name: Datasets - Initialization
        uses: ./.github/actions/aml-dataset-create
        with:
          datasetFile: datasets/*/dataset.yml
          initialize: true
          initialDataPath: data
          storageAccount: ${STORAGEACCOUNTNAME}
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
